Repository palantir/safe-logging, pull requests merged in 2019-07, with the labels that each got.

#176 Rename hasArgs to containsArgs
  changelog/@unreleased/pr-176.v2.yml
  preconditions-assertj/src/main/java/com/palantir/logsafe/testing/LoggableExceptionAssert.java
  preconditions-assertj/src/test/java/com/palantir/logsafe/testing/LoggableExceptionAssertionsTest.java
  safe-logging-refactorings/build.gradle
  safe-logging-refactorings/src/main/java/com/palantir/logsafe/refactorings/DeprecatedLoggableExceptionAssertArgs.java
  settings.gradle
  versions.props
Labels: merge when ready

#177 Fix refaster rule
  changelog/@unreleased/pr-177.v2.yml
  safe-logging-refactorings/src/main/java/com/palantir/logsafe/refactorings/DeprecatedLoggableExceptionAssertArgs.java
Labels: autorelease, merge when ready

#178 Migrate to gradle-consistent-versions
  build.gradle
  gradle.properties
  preconditions-assertj/build.gradle
  safe-logging-refactorings/build.gradle
  settings.gradle
  versions.lock
Labels: merge when ready, no changelog
